#!/bin/bash#!/bin/bash#!/bin/bash

pandoc --standalone -c style.css --from markdown --to html -o index.html Helkey.md
pandoc --standalone -c style.css --from markdown --to docx -o Helkey.docx Helkey.md

# git commit -a -m "commit message"
# git push origin gh-pages
